services:
  frontend:
    container_name: salesforce-oauth-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - PORT=${FRONTEND_PORT}
    networks:
      - salesforce-oauth

  backend:
    container_name: salesforce-oauth-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://salesforce-oauth-frontend:5173
      - PORT=${SERVER_PORT}
      - CONSUMER_KEY=${SALESFORCE_CONSUMER_KEY}
      - CONSUMER_SECRET=${SALESFORCE_CONSUMER_SECRET}
      - SERVER_URL=${SERVER_URL}
    depends_on:
      - frontend
    networks:
      - salesforce-oauth

networks:
  salesforce-oauth:
    driver: bridge